
x = (a) -> 
  a: @a
  a
  
y = x 1

name = "john"

up = `.toUpper()`

for x of [1,2,3,2*2] {
  ok true
}

unless session?
  run()
  
  
// englify at backticks arrow unless brackets_for_keywords reverse_blocks existential implicit_brackets indented_blocks string_interpolation extend_for operators implicit_return implicit_vars half_operators double_brackets class prototype super double_brackets multiline_strings pipe utils 
